### PR TITLE
Improved Footer design

### LINKED ISSUE #8: Enhancing the Footer design
The copyright section of the footer looked a bit off: 
Screenshot 2024-12-23 at 12 17 32 AM

So, I decided to update its design:
Screenshot 2024-12-23 at 12 44 17 AM

Please provide any other suggestions and any changes to the wording that could improve clarity and style.

### PR DESCRIPTION
**Pull request by akshayks13**
Screenshot 2024-12-23 at 7 29 22 PM

Improved the aesthetics of the footer 

Solved #8

### CODE REVIEW

**Comment by amri-tah** [comment]
Hey, please fix the conflicts from main and commit again

**Comment by akshayks13** [comment]
> Hey, please fix the conflicts from main and commit again

Done @amri-tah

**Review by amri-tah — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
