### PR TITLE
Added form validation for recipe pages and Improvised the form structure

### LINKED ISSUE #15: Form Validation for each recipe
There isnt any form validation for the recipe page and also needs some UI Enhancements 

And I am interested in doing this 

So @amri-tah  can I take up this

### PR DESCRIPTION
**Pull request by akshayks13**
Features Added:

- Enhanced Form Structure: The form has been consolidated into a single section, making it more visually appealing and easier to understand.
- Hover Effects for Button: Added hover effects to the submit button, improving user interaction and visual feedback.
- Simple JavaScript Form Validation: Implemented basic form validation that checks the correctness of the name and email fields. If any errors are detected, an error message is displayed below the input fields, and the borders are highlighted to indicate the issue.
I have added `recipeFormValidator.js` , a new file to handle this
- Toast Message Upon Successful Submission: A toast notification is shown after successful form submission, which also has a link which redirects the user to the catalog.html.

 This version ensures a cleaner design, more intuitive user experience, and helpful feedback for error handling and successful submission.

#15 - resolved this

### CODE REVIEW

**Comment by akshayks13** [comment]
Screenshot 2024-12-25 at 7 01 01 PM

When error in form

**Comment by akshayks13** [comment]
Screenshot 2024-12-25 at 7 02 13 PM

On successfull submission of the form

**Review by amri-tah — CHANGES_REQUESTED** [review]
This looks really good! Just some tiny changes and we are good to go:
- Can reduce the size of the toast message text
- Remove the back to recipes page link thingy

**Comment by akshayks13** [comment]
Screenshot 2024-12-31 at 1 34 40 PM

Is this nice ?

**Comment by amri-tah** [comment]
> Screenshot 2024-12-31 at 1 34 40 PM
> Is this nice ?

Please also put the "Thank you <name>," in the same linee. Font size looks fine now

**Comment by akshayks13** [comment]
Screenshot 2024-12-31 at 1 57 27 PM

Now ?

**Review by amri-tah — APPROVED** [review]

**Pull request merged**
